### PR TITLE
Hopefully removing all files that have been committed that we want ignored

### PR DESCRIPTION
**Pull request by NToppingCCS**
As I commit this, it seems to have done the trick but Conclave itself seems to be offline - so I can't fully test it's not broken anything (DigiTS is having the same issue though, so confident it's not the change).

Will test in the morning before merging, but this is good for review.

### CODE REVIEW

**Comment by NToppingCCS** [comment]
Worth checking the removed filenames as part of review to make sure nothing has been removed that we need to keep.

**Comment by ccsnareshk** [comment]
that's a good work on this. yes will review and hope this would be ok as it seems.

**Review by ccsnareshk — COMMENTED** [review]
checked all files one by one it seems all good. Only I see if we would need to push appsettings.json or similar file?

**Review by ccsnareshk — APPROVED** [review]

**Comment by NToppingCCS** [comment]
Tested and confirmed Conclave still works ok now, so this seems fine from that front too.

AppSettings we may clean up before release, but I'd rather leave it there for now to make dev easier.

**Pull request merged**
